import { NextRequest, NextResponse } from 'next/server'
import { downloadAndStoreImage, generateImageFileName } from '@/lib/firebaseStorage'

// Test endpoint
export async function GET() {
  return NextResponse.json({
    message: 'Flux Kontext Pro API is working',
    timestamp: new Date().toISOString()
  })
}

export async function POST(request: NextRequest) {
  try {
    console.log('🚀 Flux Kontext Pro API called')
    const body = await request.json()
    console.log('📝 Request body received:', {
      hasPrompt: !!body.prompt,
      hasInputImage: !!body.input_image,
      aspectRatio: body.aspect_ratio
    })
    
    const {
      prompt,
      input_image,
      seed,
      aspect_ratio,
      output_format = 'png',
      webhook_url,
      webhook_secret,
      prompt_upsampling = false,
      safety_tolerance = 2
    } = body

    // Validate required fields
    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      )
    }

    // Validate safety tolerance range
    if (safety_tolerance < 0 || safety_tolerance > 6) {
      return NextResponse.json(
        { error: 'Safety tolerance must be between 0 and 6' },
        { status: 400 }
      )
    }

    // Prepare request body for BFL API
    const requestBody: {
      prompt: string
      output_format: string
      prompt_upsampling: boolean
      safety_tolerance: number
      input_image?: string
      seed?: number
      aspect_ratio?: string
      webhook_url?: string
      webhook_secret?: string
    } = {
      prompt,
      output_format,
      prompt_upsampling,
      safety_tolerance
    }

    // Add optional fields
    if (input_image) {
      requestBody.input_image = input_image
    }

    if (seed) {
      requestBody.seed = seed
    }

    if (aspect_ratio) {
      requestBody.aspect_ratio = aspect_ratio
    }

    if (webhook_url) {
      requestBody.webhook_url = webhook_url
    }

    if (webhook_secret) {
      requestBody.webhook_secret = webhook_secret
    }

    console.log('🚀 Calling Flux Kontext Pro API:', {
      prompt: prompt.substring(0, 100) + '...',
      hasInputImage: !!input_image,
      aspectRatio: aspect_ratio,
      seed,
      promptUpsampling: prompt_upsampling,
      safetyTolerance: safety_tolerance
    })

    // Call BFL API
    const bflResponse = await fetch('https://api.bfl.ai/v1/flux-kontext-pro', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-key': process.env.FLUX_API_KEY!,
      },
      body: JSON.stringify(requestBody),
    })

    if (!bflResponse.ok) {
      const errorData = await bflResponse.text()
      console.error('BFL API Error:', bflResponse.status, errorData)

      return NextResponse.json(
        { error: `BFL API error: ${bflResponse.status} - ${errorData}` },
        { status: bflResponse.status }
      )
    }

    const data = await bflResponse.json()
    console.log('✅ BFL API Response:', { id: data.id, polling_url: data.polling_url })

    // Start polling for result
    const pollResult = await pollForResult(data.polling_url)

    if (pollResult.error) {
      return NextResponse.json(
        { error: pollResult.error },
        { status: 500 }
      )
    }

    // Store image in Firebase Storage for permanent access
    let permanentImageUrl = null
    let storagePath = null
    let storageError = null
    const originalImageUrl = pollResult.result?.sample || null

    if (originalImageUrl) {
      console.log('💾 Storing image in Firebase Storage...')
      const fileName = generateImageFileName(requestBody.prompt, 'flux-kontext-pro')
      try {
        const storageResult = await downloadAndStoreImage(originalImageUrl, fileName)

        if (storageResult.success) {
          permanentImageUrl = storageResult.url!
          storagePath = storageResult.path
          console.log('✅ Image stored permanently in Firebase:', permanentImageUrl)
        } else {
          console.error('❌ Failed to store image in Firebase:', storageResult.error)
          storageError = storageResult.error
          console.log('⚠️ Using original BFL URL as fallback (will expire)')
          permanentImageUrl = originalImageUrl
        }
      } catch (error: unknown) {
        console.error('❌ Error during upload:', error)
        return NextResponse.json(
          { error: error instanceof Error ? error.message : 'Unknown error occurred' },
          { status: 500 }
        )
      }
    } else {
      return NextResponse.json(
        { error: 'No image generated by BFL API' },
        { status: 500 }
      )
    }

    // Return structured JSON response
    const responseData = {
      success: true,
      id: data.id,
      polling_url: data.polling_url,
      result: {
        sample: permanentImageUrl  // Firebase Storage URL or fallback
      },
      imageUrl: permanentImageUrl,  // Primary image URL
      originalImageUrl: originalImageUrl,  // Original BFL URL (for reference)
      storagePath,
      timestamp: new Date().toISOString(),
      // Add metadata for better error handling
      metadata: {
        model: 'flux-kontext-pro',
        prompt: requestBody.prompt.substring(0, 100),
        aspectRatio: requestBody.aspect_ratio,
        hasInputImage: !!requestBody.input_image,
        storedInFirebase: !!storagePath,  // True only if Firebase Storage succeeded
        isTemporaryUrl: !storagePath,     // Warning flag for temporary URLs
        storageError: storageError
      }
    }

    console.log('✅ Returning successful response:', {
      id: responseData.id,
      hasImageUrl: !!responseData.imageUrl
    })

    return NextResponse.json(responseData)

  } catch (error) {
    console.error('Flux Kontext Pro API Error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// Polling function to get the result
async function pollForResult(pollingUrl: string, maxAttempts = 30, interval = 2000) {
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      console.log(`📊 Polling attempt ${attempt + 1}/${maxAttempts}`)
      
      const response = await fetch(pollingUrl, {
        headers: {
          'x-key': process.env.FLUX_API_KEY!,
        },
      })

      if (!response.ok) {
        console.error('Polling error:', response.status)
        continue
      }

      const data = await response.json()
      console.log('📊 Polling status:', data.status)

      if (data.status === 'Ready') {
        console.log('✅ Generation complete!')
        return { result: data.result }
      }

      if (data.status === 'Error' || data.status === 'Request Moderated') {
        console.error('❌ Generation failed:', data.status)
        return { error: `Generation failed: ${data.status}` }
      }

      // Wait before next poll
      await new Promise(resolve => setTimeout(resolve, interval))

    } catch (error) {
      console.error('Polling attempt failed:', error)
      
      // If it's the last attempt, return error
      if (attempt === maxAttempts - 1) {
        return { error: 'Polling failed after maximum attempts' }
      }
      
      // Wait before retry
      await new Promise(resolve => setTimeout(resolve, interval))
    }
  }

  return { error: 'Generation timed out' }
}
